llm_configuration:
  llm_model: "llama-3.3-70b-versatile"
  temperature: 0.1
  max_tokens: 2048

embedding_configuration:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

chunking_configuration:
  chunk_size: 1000
  chunk_overlap: 200
  separators:
    - "\n\n"
    - "\n"
    - ". "
    - " "
    - ""

vectorstore_configuration:
  vector_store: "faiss"
  faiss_index_path: "vector_db/faiss_index"
  top_k: 5

# env_keys:
#   GROQ_API_KEY: ""
  # LLM_API_KEY: ""



# vectorstore_configuration:
#   vector_store: "chroma"
#   persist_directory: "vector_db/chroma_store"
#   top_k: 4

# env_keys:
#   GOOGLE_API_KEY: ""
#   GROQ_API_KEY: ""
#   CHROMA_API_KEY: ""